[34m[1mwandb[0m:   74 of 74 files downloaded. 
[34m[1mwandb[0m:   1 of 1 files downloaded.
/home/danfossautonomypc/segmentation/wandb_segment/src/eval.py:45: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(model_dir))
Test loss is: 0.0729
Traceback (most recent call last):
  File "/home/danfossautonomypc/segmentation/wandb_segment/test_for_github.py", line 81, in <module>
    run.log({"table_results": test_table})
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1922, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1641, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1513, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 631, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/data_types/utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/data_types/utils.py", line 157, in val_to_json
    art = wandb.Artifact(f"run-{run.id}-{sanitized_key}", "run_table")
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 127, in __init__
    raise ValueError(
ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: run-testing github-table_results
Traceback (most recent call last):
  File "/home/danfossautonomypc/segmentation/wandb_segment/test_for_github.py", line 81, in <module>
    run.log({"table_results": test_table})
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 403, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 393, in wrapper
    return func(self, *args, **kwargs)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1922, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1641, in _log
    self._partial_history_callback(data, step, commit)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1513, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 631, in publish_partial_history
    data = history_dict_to_json(run, data, step=user_step, ignore_copy_err=True)
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/data_types/utils.py", line 54, in history_dict_to_json
    payload[key] = val_to_json(
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/data_types/utils.py", line 157, in val_to_json
    art = wandb.Artifact(f"run-{run.id}-{sanitized_key}", "run_table")
  File "/home/danfossautonomypc/.local/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 127, in __init__
    raise ValueError(
ValueError: Artifact name may only contain alphanumeric characters, dashes, underscores, and dots. Invalid name: run-testing github-table_results
